# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uploader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uploader.proto',
  package='UploaderPkg',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0euploader.proto\x12\x0bUploaderPkg\"<\n\x11\x46ileUploadRequest\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"%\n\x12\x46ileUploadResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t2d\n\x0fUploaderService\x12Q\n\nuploadFile\x12\x1e.UploaderPkg.FileUploadRequest\x1a\x1f.UploaderPkg.FileUploadResponse\"\x00(\x01\x62\x06proto3'
)




_FILEUPLOADREQUEST = _descriptor.Descriptor(
  name='FileUploadRequest',
  full_name='UploaderPkg.FileUploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UploaderPkg.FileUploadRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='UploaderPkg.FileUploadRequest.chunk', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='UploaderPkg.FileUploadRequest.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=31,
  serialized_end=91,
)


_FILEUPLOADRESPONSE = _descriptor.Descriptor(
  name='FileUploadResponse',
  full_name='UploaderPkg.FileUploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_id', full_name='UploaderPkg.FileUploadResponse.file_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=130,
)

_FILEUPLOADREQUEST.oneofs_by_name['data'].fields.append(
  _FILEUPLOADREQUEST.fields_by_name['name'])
_FILEUPLOADREQUEST.fields_by_name['name'].containing_oneof = _FILEUPLOADREQUEST.oneofs_by_name['data']
_FILEUPLOADREQUEST.oneofs_by_name['data'].fields.append(
  _FILEUPLOADREQUEST.fields_by_name['chunk'])
_FILEUPLOADREQUEST.fields_by_name['chunk'].containing_oneof = _FILEUPLOADREQUEST.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['FileUploadRequest'] = _FILEUPLOADREQUEST
DESCRIPTOR.message_types_by_name['FileUploadResponse'] = _FILEUPLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileUploadRequest = _reflection.GeneratedProtocolMessageType('FileUploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADREQUEST,
  '__module__' : 'uploader_pb2'
  # @@protoc_insertion_point(class_scope:UploaderPkg.FileUploadRequest)
  })
_sym_db.RegisterMessage(FileUploadRequest)

FileUploadResponse = _reflection.GeneratedProtocolMessageType('FileUploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADRESPONSE,
  '__module__' : 'uploader_pb2'
  # @@protoc_insertion_point(class_scope:UploaderPkg.FileUploadResponse)
  })
_sym_db.RegisterMessage(FileUploadResponse)



_UPLOADERSERVICE = _descriptor.ServiceDescriptor(
  name='UploaderService',
  full_name='UploaderPkg.UploaderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=132,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadFile',
    full_name='UploaderPkg.UploaderService.uploadFile',
    index=0,
    containing_service=None,
    input_type=_FILEUPLOADREQUEST,
    output_type=_FILEUPLOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOADERSERVICE)

DESCRIPTOR.services_by_name['UploaderService'] = _UPLOADERSERVICE

# @@protoc_insertion_point(module_scope)
